/* ****************************************************
* !!!! AUTO GENERATED FILE, DO NOT EDIT !!!!
*
* This file is auto-generated by the script version_increment_pre.py
* Contains the HTML content converted to rawliteral string in  the C header file.
* The input HTML files are stored in the resources folder.
* Current confguration: 
* 	MainPage.html 		--> index_html
* 	LogoutPage.html 		--> logout_html
* 	WebChartPage.html 		--> html_content_chart
* 	WebDataSettingsPage.html 		--> settings_html
* *****************************************************/
const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="data:image/x-icon;base64,AAABAAEAAQEAAAEAIAAwAAAAFgAAACgAAAABAAAAAgAAAAEAIAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAA==" />
    <title>Heater Control Panel</title>
    <style>
        :root {
            --primary-color: #2196F3;
            --secondary-color: #808080;
            --background-color: #f5f5f5;
            --card-background: #ffffff;
            --text-color: #333333;
            --border-radius: 8px;
            --shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            background-color: var(--background-color);
            color: var(--text-color);
        }

        header {
            background-color: var(--primary-color);
            color: white;
            padding: 1rem;
            box-shadow: var(--shadow);
        }

        .header-content {
            max-width: 1200px;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }

        .header-content > div:first-child {
            width: 100%;
            display: flex;
            flex-direction: row; /* Ensure horizontal layout */
            justify-content: flex-start; /* Start from the left */
            align-items: center;
            gap: 1rem;
        }

        .container {
            max-width: 1200px;
            margin: 2rem auto;
            padding: 0 1rem;
        }

        .card {
            background: var(--card-background);
            border-radius: var(--border-radius);
            padding: 1rem;    /* Reduced from 1.5rem */
            margin-bottom: 1rem;  /* Reduced from 1.5rem */
            box-shadow: var(--shadow);
        }

        .switch {
            position: relative;
            display: inline-block;
            width: 90px;  /* Original 60px * 1.5 */
            height: 51px; /* Original 34px * 1.5 */
        }

        .switch input {
            display: none;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            transition: .4s;
            border-radius: 34px;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 39px;  /* Original 26px * 1.5 */
            width: 39px;   /* Original 26px * 1.5 */
            left: 6px;     /* Original 4px * 1.5 */
            bottom: 6px;   /* Original 4px * 1.5 */
            background-color: white;
            transition: .4s;
            border-radius: 50%;
        }

        input:checked + .slider {
            background-color: var(--primary-color);
        }

        input:checked + .slider:before {
            transform: translateX(39px); /* Original 26px * 1.5 */
        }

        .control-group {
            display: grid;
            grid-template-columns: 70px 30px 60px 30px 30px 50px; /* Adjusted column sizes */
            gap: 0.3rem;  /* Reduced overall gap */
            align-items: center;
            margin: 0.5rem 0;
            justify-content: start;
        }

        .control-group label {
            text-align: left;
            min-width: 70px;  /* Reduced label width */
            padding-right: 0.2rem; /* Add small padding after label */
        }

        .control-group button {
            width: 30px;     /* Reduced button size */
            height: 30px;    /* Reduced button size */
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1rem; /* Adjust font size for +/- buttons */
        }

        /* Make Set button more compact */
        .control-group button[type="submit"] {
            width: auto;
            height: auto;
            padding: 0.3rem 0.6rem;
            min-width: 0;
            font-size: 0.9rem;
        }

        /* Keep units (°C, min) aligned */
        .control-group span {
            min-width: 30px;
            text-align: left;
            padding-left: 0.2rem;
        }

        button {
            background-color: var(--primary-color);
            color: white;
            border: none;
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #1976D2;
        }

        input[type="text"] {
            padding: 0.3rem;
            border: 1px solid #ddd;
            border-radius: 4px;
            width: 60px;
            text-align: center;
        }

        .temperature-display {
            font-size: 1.2rem;
            font-weight: bold;
        }

        .temperature-display h3 {
            display: flex;
            align-items: center;
            gap: 1rem;
            margin-bottom: 0.5rem;
        }

        .temperature-range {
            font-size: 1.2rem;
            font-weight: 500;
            color: var(--text-color);
            display: inline-block;
        }

        .navigation {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
        }

        .navigation a {
            text-decoration: none;
            color: var(--primary-color);
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            background: white;
            box-shadow: var(--shadow);
        }

        .navigation a:hover {
            background: #f0f0f0;
        }

        footer {
            background-color: var(--secondary-color);
            color: white;
            text-align: center;
            padding: 1rem;
            margin-top: 2rem;
        }

        #connection_status {
            padding: 0.3rem;
            color: #004900;
            font-weight: bold;
            font-size: 1rem;
            display: inline-flex; /* Change to inline-flex */
            align-items: center;
        }

        #logoutButton {
            background-color: #dc3545;
            margin-left: auto; /* Push to the right */
            white-space: nowrap; /* Prevent button text from wrapping */
        }

        #logoutButton:hover {
            background-color: #c82333;
        }

        @media (max-width: 768px) {
            .control-group {
                grid-template-columns: auto auto;
                gap: 0.5rem;
            }
            
            .control-group label {
                text-align: left;
            }

            .container {
                padding: 0.5rem;
            }
        }

        /* Make temperature range text bigger */
        .temperature-range {
            font-size: 1.4rem;
            font-weight: 500;
            color: var(--text-color);
        }

        /* Update the header styles */
        .header-content div {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
            gap: 0.5rem;
        }

        /* Update feedback text size */
        #feedback_info {
            font-size: 2em;
            margin-bottom: 1rem;
        }

        /* Update heater info text size */
        #heater {
            font-size: 1.5em;
            margin-bottom: 1rem;
        }

        /* Update temperature display sizes */
        .temperature-display h3 {
            font-size: 1.2em;
        }

        /* Keep controls inline */
        .control-group {
            display: grid;
            grid-template-columns: 100px 40px 80px 40px 40px 60px;
            gap: 0.5rem;
            align-items: center;
            margin: 1rem 0;
            justify-content: start;
        }

        /* Ensure form fields stay inline on mobile */
        @media (max-width: 768px) {
            .control-group {
                grid-template-columns: 70px 30px 60px 30px 40px 60px;
                overflow-x: auto;
                padding-bottom: 0.5rem;
            }
        }

        h1 {
            margin: 0 auto;
            text-align: center;
            width: 100%;
        }

        /* Update header and top controls styles */
        .header-content > div:first-child {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 1rem;
        }

        #connection_status {
            padding: 0.3rem;
            color: #006400;
            font-weight: bold;
            font-size: 1rem;
        }

        /* Update feedback and switch container */
        .feedback-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 1rem;
        }

        #feedback_info {
            font-size: 2em;
            margin: 0;  /* Remove margin since we're using flex */
        }

        .switch-container {
            flex-shrink: 0;  /* Prevent switch from shrinking */
        }

        /* Add to existing styles section */
        .control-group button[type="submit"].modified {
            background-color: #FFA500;  /* Yellow/Orange color */
        }

        .control-group button[type="submit"].modified:hover {
            background-color: #FF8C00;  /* Darker shade for hover */
        }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <div>
                <span id="connection_status">.</span>
                <button id="logoutButton">Logout</button>
            </div>
            <h1>Heater Control</h1>
        </div>
    </header>

    <div class="container">
        <div class="card">
            <div class="feedback-container">
                <h2 id="feedback_info">%FEEDBACK_PLACEHOLDER%</h2>
                <div class="switch-container">
                    <label class="switch">
                        <input type="checkbox" id="output" %BUTTONPLACEHOLDER%>
                        <span class="slider"></span>
                    </label>
                </div>
            </div>
        </div>

        <div class="card">
            <h3 id="heater">Loading...</h3>
            <form action="/set" class="control-group">
                <label for="termostat_min_temp">Setpoint:</label>
                <button id="minus_temp">-</button>
                <input type="text" id="termostat_min_temp" name="termostat_min_temp" value=%SETPOINT_PLACEHOLDER% maxlength="4">
                <button id="plus_temp">+</button>
                <span>°C</span>
                <button type="submit">Set</button>
            </form>

            <form action="/set" class="control-group">
                <label for="timer_on_time">Time on:</label>
                <button id="minus_min">-</button>
                <input type="text" id="timer_on_time" name="timer_on_time" value=%TIME_ON_PLACEHOLDER% maxlength="3">
                <button id="plus_min">+</button>
                <span>min</span>
                <button type="submit">Set</button>
            </form>

            <form action="/set" class="control-group">
                <label for="timer_off_time">Time off:</label>
                <button id="minus_max">-</button>
                <input type="text" id="timer_off_time" name="timer_off_time" value=%TIME_OFF_PLACEHOLDER% maxlength="3">
                <button id="plus_max">+</button>
                <span>min</span>
                <button type="submit">Set</button>
            </form>
        </div>

        <div class="card">
            <div class="temperature-display">
                <h3>
                    Puffer: <span id="puffertemp">%PUF_T_PLACEHOLDER%</span> °C
                    <span class="temperature-range">(%PUF_T_MIN_PLACEHOLDER% °C \ %PUF_T_MAX_PLACEHOLDER% °C)</span>
                </h3>
            </div>
            <div class="temperature-display">
                <h3>Heater: <span id="boilertemp">%HEAT_T_PLACEHOLDER%</span> °C</h3>
            </div>
        </div>

        <nav class="navigation">
            <a href="/chart.html">Information</a>
            <a href="/settings.html">Settings</a>
        </nav>
    </div>

    <footer>
        <h3>%VERSIONPLACEHOLDER%</h3>
    </footer>

    <!-- Keep existing script section unchanged -->
    <script>
  // Configuration object for all constants and settings
  const CONFIG = {
      ENDPOINTS: {
          CONNECTION: '/connection_status',
          HEATER_INFO: '/heating_info',
          PUFFER_TEMP: '/puffer_temperature',
          BOILER_TEMP: '/boiler_temperature',
          SLIDER_STATE: '/state_slider_button',
          FEEDBACK: '/feedback_text',
          LOGOUT: '/logout',
          LOGGEDOUT: '/logged-out',
          UPDATE: '/update',
          SET: '/set'
      },
      INTERVALS: {
          CONNECTION: 5000,
          HEATER: 1000,
          TEMPERATURE: 10000,
          FEEDBACK: 3000
      },
      LIMITS: {
          TEMPERATURE: { MIN: 10, MAX: 35, STEP: 0.1 },
          TIME_ON: { MIN: 20, MAX: 120, STEP: 10 },
          TIME_OFF: { MIN: 0, MAX: 360, STEP: 10 }
      }
  };
  
  // Utility class for API calls
  class ApiClient {
      static async fetch(endpoint, options = {}) {
          try {
              const response = await fetch(endpoint, {
                  method: options.method || 'GET',
                  headers: options.headers || {},
                  ...options
              });
              if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
              return await response.text();
          } catch (error) {
              console.error(`API call failed: ${endpoint}`, error);
              throw error;
          }
      }
  }
  
  // Class to handle data polling
  class DataPoller {
      constructor(elementId, endpoint, interval, updateCallback) {
          this.element = document.getElementById(elementId);
          this.endpoint = endpoint;
          this.interval = interval;
          this.updateCallback = updateCallback;
          this.intervalId = null;
      }
  
      start() {
          if (!this.element) return;
          this.poll();
          this.intervalId = setInterval(() => this.poll(), this.interval);
      }
  
      stop() {
          if (this.intervalId) {
              clearInterval(this.intervalId);
              this.intervalId = null;
          }
      }
  
      async poll() {
          try {
              const data = await ApiClient.fetch(this.endpoint);
              this.updateCallback(this.element, data);
          } catch (error) {
              console.error(`Polling failed for ${this.endpoint}`);
          }
      }
  }
  
  // Class to handle button controls
  class ButtonControl {
    constructor(config) {
        const { minusId, plusId, inputId, min, max, step, format } = config;
        this.minusButton = document.getElementById(minusId);
        this.plusButton = document.getElementById(plusId);
        this.input = document.getElementById(inputId);
        this.min = min;
        this.max = max;
        this.step = step;
        
        // Fix format function definition
        this.format = format || function(x) {
            const value = parseFloat(x);
            return isNaN(value) ? this.min.toString() : Math.round(value).toString();
        };
        
        // Initialize with valid value
        if (this.input) {
            const initialValue = parseFloat(this.input.value) || this.min;
            const validValue = Math.max(this.min, Math.min(this.max, initialValue));
            this.input.value = this.format(validValue);
        }
        
        this.initialValue = this.input ? this.input.value : '';
        this.setupListeners();
    }

    setupListeners() {
        if (this.minusButton) {
            this.minusButton.addEventListener('click', (e) => {
                this.handleMinus(e);
                this.checkValueChanged();
            });
        }
        if (this.plusButton) {
            this.plusButton.addEventListener('click', (e) => {
                this.handlePlus(e);
                this.checkValueChanged();
            });
        }
        if (this.input) {
            this.input.addEventListener('change', () => {
                this.validateInput();
                this.checkValueChanged();
            });
            this.input.addEventListener('input', () => this.checkValueChanged());
        }
    }

    handleMinus(event) {
        event.preventDefault();
        const currentValue = parseFloat(this.input.value) || this.min;
        const newValue = Math.max(this.min, currentValue - this.step);
        this.input.value = this.format(newValue);
    }

    handlePlus(event) {
        event.preventDefault();
        const currentValue = parseFloat(this.input.value) || this.min;
        const newValue = Math.min(this.max, currentValue + this.step);
        this.input.value = this.format(newValue);
    }

    validateInput() {
        const currentValue = parseFloat(this.input.value) || this.min;
        const validValue = Math.min(this.max, Math.max(this.min, currentValue));
        this.input.value = this.format(validValue);
    }

    checkValueChanged() {
        if (!this.input) return;
        
        const submitButton = this.input.closest('form').querySelector('button[type="submit"]');
        if (this.input.value !== this.initialValue) {
            submitButton.classList.add('modified');
        } else {
            submitButton.classList.remove('modified');
        }
    }

    // Add new method to update initialValue
    updateInitialValue() {
        if (this.input) {
            this.initialValue = this.input.value;
        }
    }
}
  
  // Connection manager class
  class ConnectionManager {
    constructor() {
        this.statusElement = document.getElementById('connection_status');
        this.lastUpdateTime = Date.now();
        this.checkInterval = 6000; // Slightly longer than polling interval
        this.connectionChecker = null;
        
        this.poller = new DataPoller(
            'connection_status',
            CONFIG.ENDPOINTS.CONNECTION,
            CONFIG.INTERVALS.CONNECTION,
            this.handleConnectionUpdate.bind(this)
        );
    }

    start() {
        this.poller.start();
        // Start connection checker
        this.connectionChecker = setInterval(() => this.checkConnection(), 1000);
    }

    handleConnectionUpdate(element, data) {
        if (!element) return;
        
        this.lastUpdateTime = Date.now();
        element.innerHTML = data;
        element.style.color = '#006400'; // Dark green
    }

    checkConnection() {
        const timeSinceLastUpdate = Date.now() - this.lastUpdateTime;
        
        if (timeSinceLastUpdate > this.checkInterval) {
            // Connection lost
            if (this.statusElement) {
                this.statusElement.innerHTML = 'Connection error!';
                this.statusElement.style.color = 'red';
            }
        }
    }
}
  
  function getFeedbackColor(feedback) {
    if (!feedback) return 'black';
    const text = feedback.toLowerCase();
    if (text.includes('error')) return 'red';
    if (text.includes('off')) return 'saddlebrown';
    if (text.includes('on')) return 'darkgreen';
    if (text.includes('hot')) return 'firebrick';
    if (text.includes('cold')) return 'blue';
    return 'black';
  }
  
  // Add this before initializeApp
  let controls = []; // Make controls accessible globally

  // Update the initializeApp function
  function initializeApp() {
      // Initialize button controls
      controls = [  // Assign to global controls array
          new ButtonControl({
              minusId: 'minus_temp',
              plusId: 'plus_temp',
              inputId: 'termostat_min_temp',
              min: CONFIG.LIMITS.TEMPERATURE.MIN,
              max: CONFIG.LIMITS.TEMPERATURE.MAX,
              step: CONFIG.LIMITS.TEMPERATURE.STEP,
              format: (x) => parseFloat(x).toFixed(1)
          }),
          new ButtonControl({
              minusId: 'minus_min',
              plusId: 'plus_min',
              inputId: 'timer_on_time',
              min: CONFIG.LIMITS.TIME_ON.MIN,
              max: CONFIG.LIMITS.TIME_ON.MAX,
              step: CONFIG.LIMITS.TIME_ON.STEP,
              format: (x) => Math.round(x).toString()
          }),
          new ButtonControl({
              minusId: 'minus_max',
              plusId: 'plus_max',
              inputId: 'timer_off_time',
              min: CONFIG.LIMITS.TIME_OFF.MIN,
              max: CONFIG.LIMITS.TIME_OFF.MAX,
              step: CONFIG.LIMITS.TIME_OFF.STEP,
              format: (x) => Math.round(x).toString()
          })
      ];
  
      // Initialize data pollers
      const pollers = [
          new DataPoller('heater', CONFIG.ENDPOINTS.HEATER_INFO, CONFIG.INTERVALS.HEATER,
              (el, data) => { el.innerHTML = data; el.style.color = 'black'; }),
          new DataPoller('puffertemp', CONFIG.ENDPOINTS.PUFFER_TEMP, CONFIG.INTERVALS.TEMPERATURE,
              (el, data) => { el.innerHTML = data; el.style.color = 'blue'; }),
          new DataPoller('boilertemp', CONFIG.ENDPOINTS.BOILER_TEMP, CONFIG.INTERVALS.TEMPERATURE,
              (el, data) => { el.innerHTML = data; el.style.color = 'red'; }),
          new DataPoller('feedback_info', CONFIG.ENDPOINTS.FEEDBACK, CONFIG.INTERVALS.FEEDBACK,
            (el, data) => { 
              el.innerHTML = data; 
              el.style.color = getFeedbackColor(data);
            }),
          new DataPoller('output', CONFIG.ENDPOINTS.SLIDER_STATE, CONFIG.INTERVALS.HEATER,
            (el, data) => { el.checked = data === '1'; })
      ];
  
      // Start pollers
      pollers.forEach(poller => poller.start());
  
      // Initialize connection manager
      const connectionManager = new ConnectionManager();
      connectionManager.start();
  
      // Setup event handlers
      setupEventHandlers();
  }
  
  // Update the setupEventHandlers function
  function setupEventHandlers() {
    // Checkbox handler
    const checkbox = document.getElementById('output');
    if (checkbox) {
        checkbox.removeAttribute('onchange');
        checkbox.addEventListener('change', async (e) => {
            try {
                e.preventDefault();
                const state = e.target.checked ? 1 : 0;
                await ApiClient.fetch(`/update?state_slider_button=${state}`, {
                    method: 'GET',
                    cache: 'no-cache'
                });
            } catch (error) {
                console.error('Failed to update checkbox state');
                e.target.checked = !e.target.checked;
            }
        });
    }

    // Logout handler
    const logoutBtn = document.getElementById('logoutButton');
    if (logoutBtn) {
        logoutBtn.addEventListener('click', async () => {
            try {
                const response = await fetch(CONFIG.ENDPOINTS.LOGOUT, {
                    method: 'GET',
                    cache: 'no-cache'
                });
                
                // 401 is expected after logout, redirect anyway
                if (response.status === 401 || response.ok) {
                    window.location.href = CONFIG.ENDPOINTS.LOGGEDOUT;
                } else {
                    throw new Error(`Unexpected status: ${response.status}`);
                }
            } catch (error) {
                if (error.message.includes('401')) {
                    // Still redirect on 401
                    window.location.href = CONFIG.ENDPOINTS.LOGGEDOUT;
                } else {
                    console.error('Logout failed:', error);
                    alert('Logout failed. Please try again.');
                }
            }
        });
    }

    // Prevent form submissions and handle them via API
    document.querySelectorAll('form').forEach(form => {
        form.addEventListener('submit', async (e) => {
            e.preventDefault();
            const formData = new FormData(form);
            const params = new URLSearchParams(formData);
            const submitButton = form.querySelector('button[type="submit"]');
            const input = form.querySelector('input[type="text"]');
            
            try {
                await ApiClient.fetch(`/set?${params.toString()}`);
                
                if (input) {
                    // Find the corresponding ButtonControl instance
                    const control = controls.find(c => c.input === input);
                    if (control) {
                        control.updateInitialValue();
                        submitButton.classList.remove('modified');
                    }
                }
            } catch (error) {
                console.error('Failed to update value:', error);
            }
        });
    });
}
  
  // Start the application when DOM is loaded
  document.addEventListener('DOMContentLoaded', initializeApp);
  </script>
</body>
</html>
)rawliteral";

const char logout_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="data:image/x-icon;base64,AAABAAEAAQEAAAEAIAAwAAAAFgAAACgAAAABAAAAAgAAAAEAIAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAA==" />
    <title>Logged Out</title>
    <style>
        :root {
            --primary-color: #2196F3;
            --secondary-color: #808080;
            --background-color: #f5f5f5;
            --card-background: #ffffff;
            --text-color: #333333;
            --border-radius: 8px;
            --shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            background-color: var(--background-color);
            color: var(--text-color);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header {
            background-color: var(--primary-color);
            color: white;
            padding: 1rem;
            box-shadow: var(--shadow);
        }

        .header-content {
            max-width: 1200px;
            margin: 0 auto;
            text-align: center;
        }

        .container {
            max-width: 1200px;
            margin: 2rem auto;
            padding: 0 1rem;
            flex-grow: 1;
        }

        .card {
            background: var(--card-background);
            border-radius: var(--border-radius);
            padding: 1.5rem;
            margin-bottom: 1rem;
            box-shadow: var(--shadow);
            text-align: center;
        }

        h1 {
            margin-bottom: 1rem;
        }

        p {
            margin: 1rem 0;
            font-size: 1.1rem;
        }

        strong {
            color: #dc3545;
        }

        a {
            color: var(--primary-color);
            text-decoration: none;
            font-weight: 500;
            transition: color 0.3s;
        }

        a:hover {
            color: #1976D2;
        }

        footer {
            background-color: var(--secondary-color);
            color: white;
            text-align: center;
            padding: 1rem;
            margin-top: auto;
        }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Logged Out</h1>
        </div>
    </header>

    <div class="container">
        <div class="card">
            <p>You have been logged out successfully.</p>
            <p><a href="/">Return to homepage</a></p>
            <p><strong>Note:</strong> Please close all web browser tabs to complete the logout process.</p>
        </div>
    </div>

    <footer>
        <p>Heater Control System</p>
    </footer>
</body>
</html>
)rawliteral";

const char html_content_chart[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Information</title>
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script src="https://code.highcharts.com/stock/modules/data.js"></script>
    <style>
        :root {
            --primary-color: #2196F3;
            --secondary-color: #808080;
            --background-color: #f5f5f5;
            --card-background: #ffffff;
            --text-color: #333333;
            --border-radius: 8px;
            --shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            background-color: var(--background-color);
            color: var(--text-color);
        }

        header {
            background-color: var(--primary-color);
            color: white;
            padding: 1rem;
            box-shadow: var(--shadow);
        }

        .header-content {
            max-width: 1200px;
            margin: 0 auto;
            text-align: center;
        }

        .container {
            max-width: 1200px;
            margin: 2rem auto;
            padding: 0 1rem;
        }

        .card {
            background: var(--card-background);
            border-radius: var(--border-radius);
            padding: 1rem;
            margin-bottom: 1rem;
            box-shadow: var(--shadow);
        }

        #container {
            width: 100%;
            height: 500px;
            margin-bottom: 1rem;
        }

        /* Form styling */
        form {
            margin: 1rem 0;
            display: flex;
            gap: 1rem;
            align-items: center;
        }

        select {
            padding: 0.5rem;
            border: 1px solid #ddd;
            border-radius: var(--border-radius);
            background-color: white;
        }

        button, input[type="submit"] {
            background-color: var(--primary-color);
            color: white;
            border: none;
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover, input[type="submit"]:hover {
            background-color: #1976D2;
        }

        /* Feedback codes styling */
        ul {
            list-style-type: none;
            padding: 0;
        }

        ul li {
            padding: 0.5rem 0;
            border-bottom: 1px solid #eee;
        }

        ul li:last-child {
            border-bottom: none;
        }

        /* Navigation styling */
        nav {
            margin-top: 1rem;
        }

        nav ul {
            display: flex;
            gap: 1rem;
        }

        nav a {
            text-decoration: none;
            color: var(--primary-color);
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            background: white;
            box-shadow: var(--shadow);
            transition: background-color 0.3s;
        }

        nav a:hover {
            background: #f0f0f0;
        }

        /* Data points counter styling */
        #len_id {
            font-weight: bold;
            color: var(--primary-color);
        }

        footer {
            background-color: var(--secondary-color);
            color: white;
            text-align: center;
            padding: 1rem;
            margin-top: 2rem;
        }

        @media (max-width: 768px) {
            .container {
                padding: 0.5rem;
            }

            form {
                flex-direction: column;
                align-items: stretch;
            }

            #container {
                height: 400px;
            }
        }

        /* Add to existing style section */
        @keyframes feedback-success {
            0% { background-color: transparent; }
            50% { background-color: rgba(40, 167, 69, 0.2); }
            100% { background-color: transparent; }
        }

        form.feedback-success {
            animation: feedback-success 0.8s ease-out;
        }

        input[type="submit"].modified {
            background-color: #FFA500 !important;
        }

        input[type="submit"].modified:hover {
            background-color: #FF8C00 !important;
        }

        .feedback-codes {
            display: flex;
            flex-wrap: wrap;
            gap: 1rem;
            padding: 0.5rem 0;
        }

        .feedback-codes span {
            background: var(--background-color);
            padding: 0.3rem 0.8rem;
            border-radius: var(--border-radius);
            font-size: 0.9rem;
            white-space: nowrap;
        }

        .compact-list {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 0.5rem;
            padding: 0.5rem;
            list-style: none;
        }

        .compact-list li {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.3rem;
            border: none;
        }

        .compact-list span {
            background: var(--background-color);
            padding: 0.2rem 0.5rem;
            border-radius: var(--border-radius);
            font-weight: bold;
            min-width: 2.5rem;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Information</h1>
        </div>
    </header>

    <div class="container">
        <div class="card">
            <div id="container"></div>
            <p>Stored data points: <span id="len_id">0</span></p>
        </div>

        <div class="card">
            <form action="/set">
                <label for="store_history_data">Store data:</label>
                <select name="store_history_data" id="store_history_data">
                    <option value="0">disable</option>
                    <option value="1">enable</option>
                </select>
                <input type="submit" value="Save">
            </form>
        </div>
        <div class="card">
            <h2>Feedback codes</h2>
            <ul class="compact-list">
                <li><span>2550</span>Control error</li>
                <li><span>30</span>Puffer overheat</li>
                <li><span>20</span>Heating pump ON</li>
                <li><span>10</span>Heating pump OFF</li>
                <li><span>0</span>Puffer low temp</li>
            </ul>
        </div>

        <nav>
            <ul>
                <li><a href="/">Control panel</a></li>
            </ul>
        </nav>
    </div>

    <footer>
        <p>Heater Control System</p>
    </footer>

    <script>
// Utility class for API calls
class ApiClient {
    static async fetch(endpoint, options = {}) {
        try {
            const response = await fetch(endpoint, {
                method: options.method || 'GET',
                headers: options.headers || {},
                ...options
            });
            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
            return await response.text();
        } catch (error) {
            console.error(`API call failed: ${endpoint}`, error);
            throw error;
        }
    }
}

// Setup form handlers
function setupFormHandlers() {
    document.querySelectorAll('form').forEach(form => {
        const select = form.querySelector('select');
        const submitButton = form.querySelector('input[type="submit"]');
        
        if (select && submitButton) {
            let initialValue = select.value;

            // Track changes
            select.addEventListener('change', () => {
                if (select.value !== initialValue) {
                    submitButton.classList.add('modified');
                } else {
                    submitButton.classList.remove('modified');
                }
            });

            // Handle form submission
            form.addEventListener('submit', async (e) => {
                e.preventDefault();
                const formData = new FormData(form);
                const params = new URLSearchParams(formData);
                
                try {
                    await ApiClient.fetch(`/set?${params.toString()}`);
                    initialValue = select.value;
                    submitButton.classList.remove('modified');
                    
                    // Add success feedback animation
                    form.classList.remove('feedback-success');
                    void form.offsetWidth; // Force reflow
                    form.classList.add('feedback-success');
                    setTimeout(() => form.classList.remove('feedback-success'), 800);
                } catch (error) {
                    console.error('Failed to update value:', error);
                }
            });
        }
    });
}

// Initialize form handlers when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    setupFormHandlers();
});

  // update functions
  setInterval(function ( ) {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      var e = document.getElementById("len_id");
      e.innerHTML = this.responseText;
      e.style.color = 'red'; 
    }
  };
  xhttp.open("GET", "/history_len", true);
  xhttp.send();
}, 1000 ) ;
  // chart updater script
  var chart_Fire_Info = Highcharts.stockChart('container', {
      chart: {
          backgroundColor: '#f1f1f1',
          type: 'line'
      },
       rangeSelector: {
        selected: 1
      },
      title: {
          text: ''
      },
      yAxis: {
          title: {
              text: ''
          },
          plotLines: [{
              value: 100, 
              color: 'gray',
              dashStyle: 'shortdash',
              width: 2,
              label: {
                  text: ''
              }
			      }
          ]
      },
      xAxis: { 
        title: { 
          text: 'Time'
          }, 
        type: 'datetime'
      },
      plotOptions: {
          series: {
              label: {
                  connectorAllowed: true
              },
          }
      },
  
  series: [{
          name: 'Feedback Code (see below)',  //y_value_0
          color: 'orange',
          data: [%FEEDBACK_DATA_PLACEHODLER%]
      },{
          name: 'Puffer (&deg;C)',  //y_value_1
          color: 'blue',
          data: [%PUFFER_DATA_PLACEHODLER%]
      },{
          name: 'Time Remaining (min)',  //y_value_3
          color: 'yellow',
          data: [%TIME_REMAINING_DATA_PLACEHODLER%]
      },{
          name: 'Room temperature (&deg;C)',  //y_value_5
          color: 'black',
          data: [%ROOM_DATA_PLACEHODLER%]
      },{
          name: 'Set room temp (&deg;C)',  //y_value_6
          color: 'grey',
          data: [%ROOM_TARGET_DATA_PLACEHODLER%]
      },{
          name: 'Heater (&deg;C)',  //y_value_7
          color: 'red',
          data: [%HEATER_DATA_PLACEHODLER%]
      }],
  
  });
  setInterval(function ( ) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        var current_time = new Date();
        const timezone_offset = current_time.getTimezoneOffset() * 60 * 1000;
        //console.log(timezone_offset);
        var response_str = this.responseText;
        var x = current_time.getTime() - timezone_offset,
            y_value_0 =  parseFloat(response_str.split("|")[0]);
            y_value_1 =  parseFloat(response_str.split("|")[1]);
            y_value_2 =  parseFloat(response_str.split("|")[2]);
            y_value_3 =  parseFloat(response_str.split("|")[3]);
            y_value_4 =  parseFloat(response_str.split("|")[4]);
            y_value_5 =  parseFloat(response_str.split("|")[5]);
        //console.log(this.responseText);
        //values to be filled in
        //Value 0
        if(chart_Fire_Info.series[0].data.length > 600) {
          chart_Fire_Info.series[0].addPoint([x, y_value_0], true, true, true);
        } else {
          chart_Fire_Info.series[0].addPoint([x, y_value_0], true, false, true);
        }
        //Value 1
        if(chart_Fire_Info.series[1].data.length > 600) {
          chart_Fire_Info.series[1].addPoint([x, y_value_1], true, true, true);
        } else {
          chart_Fire_Info.series[1].addPoint([x, y_value_1], true, false, true);
        }
        //Value 2
        if(chart_Fire_Info.series[2].data.length > 600) {
          chart_Fire_Info.series[2].addPoint([x, y_value_2], true, true, true);
        } else {
          chart_Fire_Info.series[2].addPoint([x, y_value_2], true, false, true);
        }
        //Value 3
        if(chart_Fire_Info.series[3].data.length > 600) {
          chart_Fire_Info.series[3].addPoint([x, y_value_3], true, true, true);
        } else {
          chart_Fire_Info.series[3].addPoint([x, y_value_3], true, false, true);
        }
        //Value 4
        if(chart_Fire_Info.series[4].data.length > 600) {
          chart_Fire_Info.series[4].addPoint([x, y_value_4], true, true, true);
        } else {
          chart_Fire_Info.series[4].addPoint([x, y_value_4], true, false, true);
        }
        //Value 5
        if(chart_Fire_Info.series[5].data.length > 600) {
          chart_Fire_Info.series[5].addPoint([x, y_value_5], true, true, true);
        } else {
          chart_Fire_Info.series[5].addPoint([x, y_value_5], true, false, true);
        }
      }
    };
    xhttp.open("GET", "/chart_info", true);
    xhttp.send();
  }, 60000 ) ; // every minute
  </script>
</body>
</html>
)rawliteral";

const char settings_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="data:image/x-icon;base64,AAABAAEAAQEAAAEAIAAwAAAAFgAAACgAAAABAAAAAgAAAAEAIAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAA==" />
    <title>Settings</title>
    <style>
        :root {
            --primary-color: #2196F3;
            --secondary-color: #808080;
            --background-color: #f5f5f5;
            --card-background: #ffffff;
            --text-color: #333333;
            --border-radius: 8px;
            --shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            background-color: var(--background-color);
            color: var(--text-color);
        }

        header {
            background-color: var(--primary-color);
            color: white;
            padding: 1rem;
            box-shadow: var(--shadow);
        }

        .header-content {
            max-width: 1200px;
            margin: 0 auto;
            text-align: center;
        }

        .container {
            max-width: 1200px;
            margin: 2rem auto;
            padding: 0 1rem;
        }

        .card {
            background: var(--card-background);
            border-radius: var(--border-radius);
            padding: 1rem;
            margin-bottom: 1rem;
            box-shadow: var(--shadow);
        }

        /* Update form and input styling */
        form {
            display: grid;
            grid-template-columns: 200px 150px auto;  /* Reduced column widths */
            gap: 0.5rem;  /* Reduced gap */
            align-items: center;
            margin: 0.4rem 0;  /* Reduced margin */
        }

        label {
            display: inline-block;
            margin: 0;
            font-weight: 500;
            text-align: left;
            font-size: 0.95rem;  /* Slightly smaller font */
        }

        input[type="text"], select {
            padding: 0.4rem;  /* Reduced padding */
            border: 1px solid #ddd;
            border-radius: 4px;
            width: 150px;  /* Reduced width */
            text-align: center;
            margin: 0;
            font-size: 0.95rem;  /* Slightly smaller font */
        }

        input[type="submit"] {
            width: min-content;  /* Fit content width */
            padding: 0.3rem 0.6rem;  /* Reduced padding */
            margin: 0;
            white-space: nowrap;
            font-size: 0.9rem;  /* Slightly smaller font */
            min-width: 50px;  /* Minimum width for the save button */
        }

        button, input[type="submit"] {
            background-color: var(--primary-color);
            color: white;
            border: none;
            border-radius: var(--border-radius);
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover, input[type="submit"]:hover {
            background-color: #1976D2;
        }

        .action-buttons {
            display: flex;
            justify-content: space-between;
            margin-bottom: 1rem;
            flex-wrap: wrap;
            gap: 0.5rem;
        }

        .action-buttons a {
            color: white;  /* Changed to white for better contrast */
            text-decoration: none;
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            box-shadow: var(--shadow);
            transition: background-color 0.3s;
        }

        /* Add specific button colors */
        .action-buttons a[href="/flash_uno"] {
            background-color: #B8860B;  /* Dark Yellow */
        }

        .action-buttons a[href="/disconnect"] {
            background-color: #FF4500;  /* Deep Orange */
        }

        .action-buttons a[href="/reset_uno"],
        .action-buttons a[href="/reset_esp"] {
            background-color: #DC3545;  /* Red */
        }

        /* Hover states */
        .action-buttons a[href="/flash_uno"]:hover {
            background-color: #8B6508;  /* Darker Yellow */
        }

        .action-buttons a[href="/disconnect"]:hover {
            background-color: #CC3700;  /* Darker Orange */
        }

        .action-buttons a[href="/reset_uno"]:hover,
        .action-buttons a[href="/reset_esp"]:hover {
            background-color: #C82333;  /* Darker Red */
        }

        nav {
            margin-top: 2rem;
        }

        nav ul {
            list-style: none;
            display: flex;
            gap: 1rem;
        }

        nav a {
            text-decoration: none;
            color: var(--primary-color);
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            background: white;
            box-shadow: var(--shadow);
        }

        nav a:hover {
            background: #f0f0f0;
        }

        .uptime-info {
            margin-top: 1rem;
            font-size: 1.1rem;
        }

        #uno_uptime_id {
            color: blue;
            font-weight: bold;
        }

        #esp_uptime_id {
            color: green;
            font-weight: bold;
        }

        footer {
            background-color: var(--secondary-color);
            color: white;
            text-align: center;
            padding: 1rem;
            margin-top: 2rem;
        }

        /* Update mobile responsiveness */
        @media (max-width: 768px) {
            .container {
                padding: 0.5rem;
            }

            .action-buttons {
                flex-direction: column;
            }

            nav ul {
                flex-direction: column;
            }

            form {
                grid-template-columns: 1fr;
                gap: 0.5rem;
            }

            input[type="text"], select {
                width: 100%;
            }
        }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Settings</h1>
        </div>
    </header>

    <div class="container">
        <div class="card">
            <div class="action-buttons">
                <a href="/flash_uno" onclick="return confirm('Are you sure you want to program the UNO controller?');">Flash UNO</a>
                <a href="/disconnect" onclick="return confirm('Are you sure you want to disconnect and reset wifi settings?');">Reset WIFI</a>
                <a href="/reset_uno" onclick="return confirm('Are you sure you want to reboot the UNO controller?');">Reset UNO</a>
                <a href="/reset_esp" onclick="return confirm('Are you sure you want to reboot the ESP controller?');">Reset ESP</a>
            </div>
        </div>

        <div class="card">
            <h2>Heating settings</h2>
            <form action="/set">
                <label for="heating_mode">Heating mode:</label>
                <select name="heating_mode" id="heating_mode">
                    %HEATING_MODE_SELECT_PLACEHOLDER%
                </select>
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="termostat_min_temp">Temperature setpoint:</label>
                <input type="text" id="termostat_min_temp" name="termostat_min_temp" value="%AMBIENT_MIN_TEMP_PLACEHOLDER%" maxlength="4">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="timer_on_time">Timer on time:</label>
                <input type="text" id="timer_on_time" name="timer_on_time" value="%TIMER_ON_PLACEHOLDER%" maxlength="3">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="timer_off_time">Timer off time:</label>
                <input type="text" id="timer_off_time" name="timer_off_time" value="%TIMER_OFF_PLACEHOLDER%" maxlength="3">
                <input type="submit" value="Save">
            </form>
        </div>

        <div class="card">
            <h2>Puffer settings</h2>
            <form action="/set">
                <label for="min_puffer_temp">Minimum puffer temperature:</label>
                <input type="text" id="min_puffer_temp" name="min_puffer_temp" value="%PUFFER_MIN_PLACEHOLDER%" maxlength="2">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="max_puffer_temp">Maximum puffer temperature:</label>
                <input type="text" id="max_puffer_temp" name="max_puffer_temp" value="%PUFFER_MAX_PLACEHOLDER%" maxlength="2">
                <input type="submit" value="Save">
            </form>
        </div>

        <div class="card">
            <h2>MQTT Settings</h2>
            <form action="/set">
                <label for="mqtt_state">MQTT Connection:</label>
                <select id="mqtt_state" name="mqtt_state">
                    <option value="1" %MQTT_ENABLED_SELECTED%>Enabled</option>
                    <option value="0" %MQTT_DISABLED_SELECTED%>Disabled</option>
                </select>
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="broker_ip">MQTT Broker IP:</label>
                <input type="text" 
                       id="broker_ip" 
                       name="broker_ip" 
                       maxlength="45" 
                       value="%BROKER_IP_PLACEHOLDER%" 
                       title="Please enter a valid IP address (e.g. 192.168.1.100) or .local hostname (e.g. mydevice.local)">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="mqtt_port">MQTT Port:</label>
                <input type="text" id="mqtt_port" 
                       name="mqtt_port" 
                       value="%MQTT_PORT_PLACEHOLDER%"
                       maxlength="5" 
                       pattern="^[1-9][0-9]{0,4}$" 
                       title="Please enter a valid port number (1-65535)" 
                       min="1" max="65535">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="mqtt_user">MQTT Username:</label>
                <input type="text" 
                       id="mqtt_user" 
                       name="mqtt_user" 
                       value="%MQTT_USER_PLACEHOLDER%" 
                       maxlength="20" 
                       pattern="^[a-zA-Z0-9_]+$" 
                       title="Please enter a valid username (letters, numbers, and underscores only)">
                <input type="submit" value="Save">
            </form>

            <form action="/set">
                <label for="mqtt_pass">MQTT Password:</label>
                <input type="text" 
                       id="mqtt_pass" 
                       name="mqtt_pass" 
                       value="%MQTT_PASS_PLACEHOLDER%" 
                       maxlength="20" 
                       pattern="^[a-zA-Z0-9_]+$" 
                       title="Please enter a valid password (letters, numbers, and underscores only)">
                <input type="submit" value="Save">
            </form>
        </div>

        <div class="uptime-info">
            <p>Uno uptime: <span id="uno_uptime_id"></span></p>
            <p>Esp uptime: <span id="esp_uptime_id"></span></p>
        </div>

        <nav>
            <ul>
                <li><a href="/">Control panel</a></li>
                <li><a href="/webserial">Web serial</a></li>
            </ul>
        </nav>
    </div>

    <footer>
        <p>Heater Control System</p>
    </footer>

    <script>
        // Update the polling code to use modern fetch API
        function startPolling(elementId, endpoint, interval, color) {
            setInterval(async () => {
                try {
                    const response = await fetch(endpoint);
                    if (response.ok) {
                        const data = await response.text();
                        const element = document.getElementById(elementId);
                        if (element) {
                            element.innerHTML = data;
                            element.style.color = color;
                        }
                    }
                } catch (error) {
                    console.error(`Polling failed for ${endpoint}:`, error);
                }
            }, interval);
        }

        // Add this CSS for feedback animations
        const style = document.createElement('style');
        style.textContent = `
            @keyframes feedback-success {
                0% { background-color: transparent; }
                50% { background-color: rgba(40, 167, 69, 0.2); }
                100% { background-color: transparent; }
            }
            
            form.feedback-success {
                animation: feedback-success 0.8s ease-out;
            }
            
            input[type="submit"].modified {
                background-color: #FFA500 !important;
            }
        `;
        document.head.appendChild(style);

        // Utility class for API calls
        class ApiClient {
            static async fetch(endpoint, options = {}) {
                try {
                    const response = await fetch(endpoint, {
                        method: options.method || 'GET',
                        headers: options.headers || {},
                        ...options
                    });
                    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
                    return await response.text();
                } catch (error) {
                    console.error(`API call failed: ${endpoint}`, error);
                    throw error;
                }
            }
        }

        // Setup form handlers
        function setupFormHandlers() {
            document.querySelectorAll('form').forEach(form => {
                const input = form.querySelector('input[type="text"], select');
                const submitButton = form.querySelector('input[type="submit"]');
                
                if (input && submitButton) {
                    let initialValue = input.value;

                    // Track changes
                    input.addEventListener('input', () => {
                        if (input.value !== initialValue) {
                            submitButton.classList.add('modified');
                        } else {
                            submitButton.classList.remove('modified');
                        }
                    });

                    // Handle form submission
                    form.addEventListener('submit', async (e) => {
                        e.preventDefault();
                        const formData = new FormData(form);
                        const params = new URLSearchParams(formData);
                        
                        try {
                            await ApiClient.fetch(`/set?${params.toString()}`);
                            initialValue = input.value;
                            submitButton.classList.remove('modified');
                            
                            // Add success feedback animation
                            form.classList.remove('feedback-success');
                            void form.offsetWidth; // Force reflow
                            form.classList.add('feedback-success');
                            setTimeout(() => form.classList.remove('feedback-success'), 800);
                        } catch (error) {
                            console.error('Failed to update value:', error);
                        }
                    });
                }
            });
        }

        // Update the initialization
        document.addEventListener('DOMContentLoaded', () => {
            // Existing polling code
            startPolling('uno_uptime_id', '/uno_uptime', 1000, 'blue');
            startPolling('esp_uptime_id', '/esp_uptime', 1000, 'green');
            
            // Setup form handlers
            setupFormHandlers();
        });
    </script>
</body>
</html>

)rawliteral";

